"""
@generated by mypy-protobuf.  Do not edit manually!
isort:skip_file
"""
import abc
import vtsserving.grpc.v1.service_pb2
import grpc

class BentoServiceStub:
    """a gRPC BentoServer."""

    def __init__(self, channel: grpc.Channel) -> None: ...
    Call: grpc.UnaryUnaryMultiCallable[
        vtsserving.grpc.v1.service_pb2.Request,
        vtsserving.grpc.v1.service_pb2.Response,
    ]
    """Call handles methodcaller of given API entrypoint."""

class BentoServiceServicer(metaclass=abc.ABCMeta):
    """a gRPC BentoServer."""

    @abc.abstractmethod
    def Call(
        self,
        request: vtsserving.grpc.v1.service_pb2.Request,
        context: grpc.ServicerContext,
    ) -> vtsserving.grpc.v1.service_pb2.Response:
        """Call handles methodcaller of given API entrypoint."""

def add_BentoServiceServicer_to_server(servicer: BentoServiceServicer, server: grpc.Server) -> None: ...
