blank_issues_enabled: true
version: 2.1
contact_links:
  - name: VtsServing's Documentation
    url: https://docs.vtsserving.org/en/latest/
    about: For more information about VtsServing's tutorials, guides, API references and architectures deep-dive.
  - name: VtsServing Discussions
    url: https://github.com/vtsserving/VtsServing/discussions
    about: Please ask general questions here.
  - name: VtsServing Slack Community
    url: https://join.slack.vtsserving.org
    about: For connecting with others in the community.
  - name: VtsServing Enterprise Support
    url: contact@vtsserving.ai
    about: Contact the VtsServing team for support.
  - name: VtsServing Blog
    url: modelserving.com
    about: Read the latest blogs/updates from community and the VtsServing team. 
