# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

from vtsserving.grpc.v1alpha1 import service_pb2 as vtsserving_dot_grpc_dot_v1alpha1_dot_service__pb2


class VtsServiceStub(object):
    """a gRPC VtsServer.
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Call = channel.unary_unary(
                '/vtsserving.grpc.v1alpha1.VtsService/Call',
                request_serializer=vtsserving_dot_grpc_dot_v1alpha1_dot_service__pb2.Request.SerializeToString,
                response_deserializer=vtsserving_dot_grpc_dot_v1alpha1_dot_service__pb2.Response.FromString,
                )


class VtsServiceServicer(object):
    """a gRPC VtsServer.
    """

    def Call(self, request, context):
        """Call handles methodcaller of given API entrypoint.
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_VtsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Call': grpc.unary_unary_rpc_method_handler(
                    servicer.Call,
                    request_deserializer=vtsserving_dot_grpc_dot_v1alpha1_dot_service__pb2.Request.FromString,
                    response_serializer=vtsserving_dot_grpc_dot_v1alpha1_dot_service__pb2.Response.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'vtsserving.grpc.v1alpha1.VtsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class VtsService(object):
    """a gRPC VtsServer.
    """

    @staticmethod
    def Call(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/vtsserving.grpc.v1alpha1.VtsService/Call',
            vtsserving_dot_grpc_dot_v1alpha1_dot_service__pb2.Request.SerializeToString,
            vtsserving_dot_grpc_dot_v1alpha1_dot_service__pb2.Response.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
